name: event_reminder_app
description: "EventRELY - A reminder app with clean architecture"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  
  # HTTP Client
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0
  
  # UI
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  
  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Notifications and Reminders
  speech_to_text: ^7.0.0
  permission_handler: ^11.1.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1


# ConfiguraciÃ³n del icono
flutter_launcher_icons:
  android: true
  ios: true

  # ANDROID
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/foreground_icon.png"

  # IOS
  image_path_ios: "assets/icon/icon.png"

flutter:
  uses-material-design: true
