name: event_reminder_app
description: "EventRELY - Sistema de recordatorios con Clean Architecture"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Network
  http: ^1.1.0
  
  # Local Notifications
  flutter_local_notifications: ^17.2.3 
  timezone: ^0.9.2
  
  # Date & Time
  intl: ^0.20.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Localizations
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
